=== nagamaniganjam23/ureg-system-API/ureg-system-api/src/main/resources/api/Schemas/customer.json
{
   "definitions": {},
   "$schema": "http://json-schema.org/draft-07/schema#",
   "$id": "http://example.com/root.json",
   "type": "object",
   "title": "The Root Schema",
   "required": [
     "salesforceDigitalProfileId",
     "countryCode",
     "email",
     "firstName",
     "lastName",
     "channelType",
     "channelName"
   ],
   "properties": {
     "salesforceDigitalProfileId": {
       "$id": "#/properties/salesforceDigitalProfileId",
       "type": "string",
       "title": "The Salesforcedigitalprofileid Schema",
       "default": "",
       "examples": [
         "hfghf"
       ],
       "maxLength": 18,
       "pattern": "^(.*)$"
     },
     "countryCode": {
       "$id": "#/properties/countryCode",
       "type": "string",
       "title": "The Countrycode Schema",
       "default": "",
       "examples": [
         "91"
       ],
       "maxLength": 2,
       "pattern": "^(.*)$"
     },
     "displayName": {
       "$id": "#/properties/displayName",
       "type": "string",
       "title": "The Displayname Schema",
       "default": "",
       "examples": [
         "mani"
       ],
       "maxLength": 30,
       "pattern": "^(.*)$"
     },
     "displayNameEditable": {
       "$id": "#/properties/displayNameEditable",
       "type": "boolean",
       "title": "The Displaynameeditable Schema",
       "default": false,
       "examples": [
         true
       ]
     },
     "email": {
       "$id": "#/properties/email",
       "type": "string",
       "title": "The Email Schema",
       "default": "",
       "examples": [
         "mani@gmail.com"
       ],
       "pattern": "^(.*)$"
     },
     "firstName": {
       "$id": "#/properties/firstName",
       "type": "string",
       "title": "The Firstname Schema",
       "default": "",
       "examples": [
         "mani"
       ],
       "maxLength": 50,
       "pattern": "^(.*)$"
     },
     "lastName": {
       "$id": "#/properties/lastName",
       "type": "string",
       "title": "The Lastname Schema",
       "default": "",
       "examples": [
         "Ganjam"
       ],
       "maxLength": 50,
       "pattern": "^(.*)$"
     },
     "postalCode": {
       "$id": "#/properties/postalCode",
       "type": "string",
       "title": "The Postalcode Schema",
       "default": "",
       "examples": [
         "5463278"
       ],
       "maxLength": 10,
       "pattern": "^(.*)$"
     },
     "phone": {
       "$id": "#/properties/phone",
       "type": "string",
       "title": "The Phone Schema",
       "default": "",
       "examples": [
         "65984573095"
       ],
       "maxLength": 25,
       "pattern": "^(.*)$"
     },
     "phoneType": {
       "$id": "#/properties/phoneType",
       "type": "string",
       "title": "The Phonetype Schema",
       "default": "",
       "examples": [
         "xyx"
       ],
       "maxLength": 25,
       "pattern": "^(.*)$"
     },
     "channelType": {
       "$id": "#/properties/channelType",
       "type": "string",
       "title": "The Channeltype Schema",
       "default": "",
       "examples": [
         "dkjfflk"
       ],
       "maxLength": 10,
       "pattern": "^(.*)$"
     },
     "channelName": {
       "$id": "#/properties/channelName",
       "type": "string",
       "title": "The Channelname Schema",
       "default": "",
       "examples": [
         "abc"
       ],
       "maxLength": 10,
       "pattern": "^(.*)$"
     },
     "companyName": {
       "$id": "#/properties/companyName",
       "type": "string",
       "title": "The Companyname Schema",
       "default": "",
       "examples": [
         "invenio"
       ],
       "maxLength": 512,
       "pattern": "^(.*)$"
     },
     "jobTitle": {
       "$id": "#/properties/jobTitle",
       "type": "string",
       "title": "The Jobtitle Schema",
       "default": "",
       "examples": [
         "con"
       ],
       "maxLength": 512,
       "pattern": "^(.*)$"
     },
     "dobMonth": {
       "$id": "#/properties/dobMonth",
       "type": "integer",
       "title": "The Dobmonth Schema",
       "default": 0,
       "examples": [

       ],
       "maxLength": 512
     },
     "dobYear": {
       "$id": "#/properties/dobYear",
       "type": "integer",
       "title": "The Dobyear Schema",
       "default": 0,
       "examples": [

       ],
       "maxLength": 512
     }
   }
 }

=== nagamaniganjam23/ureg-system-API/ureg-system-api/src/main/resources/api/Examples/create-cust-digital.json
{
"salesforceDigitalProfileId":"hfghf",
"countryCode":"91",
"displayName":"mani",
"displayNameEditable":true,
"email":"mani@gmail.com",

"firstName":"mani",
"lastName":"Ganjam",

"postalCode":"5463278",
"phone":"65984573095",
"phoneType":"xyx",
"channelType":"dkjfflk",
"channelName":"abc",

"companyName":"invenio",
"jobTitle":"con",
"dobMonth":2,
"dobYear":1994

}
